version: '2.1'
# rethinkdb demonstration of the Autopilot pattern
services:

# ---------------------------------------------------
# Consul as a service discovery tier
  consul:
    image: autopilotpattern/consul:${TAG:-latest}
    labels:
      - triton.cns.services=cas-consul
      - com.joyent.package=dds-128m
    restart: always
    mem_limit: 128m
    ports:
      - 8500
    network_mode: bridge
    environment:
      - CONSUL=rtdb-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
    command: >
      /usr/local/bin/containerpilot
